version: '3.5'

services:

  reports-postgres:
    image: postgres:13.4-alpine
    container_name: reports-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
